# Templated passwords as `clone-throat-octagon-darkness-emission` are written to make sure our
# would become part of the password.
# Adding `strong` in the template will create longer passwords and is used for the
# passwords which almost never need to be manually typed.

# Password for the MySQL replication user.
# Set this to enable master-master replication between two domservers.
#REPLICATION_PASSWORD: abruptly-grope-grower-employer-tank

# Database user password.
DB_PASSWORD: omega-graves-boring-charger-wasp

# Credentials for the judgehost.
JUDGEHOST_USER: judgehost
JUDGEHOST_PASSWORD: ripple-frail-balsamic-passcode-octopus

# Username and password to be used in .netrc files on admin machines
ADMIN_USER: admin
ADMIN_PASSWORD: neuter-nectar-revisit

# Password for domjudge shell user
# Set this to enable a password on the 'domjudge' shell accounts
# created on the domserver and judgehosts.
#DJ_SHELL_USER_PW: pastel-snuff-dial

# Accounts to create when setting up the CDS
CDS_ACCOUNTS:
    - username: admin
      password: uncross-staunch-rural
      type: admin
    - username: presAdmin
      password: sandbar-gratify-bazooka
      type: admin
    - username: presentation
      password: sierra-scoff-greasily
      type: public
    #- username: blue
    #  password: blu3
    #  type: staff
    #- username: balloon
    #  password: balloonPr1nter
    #  type: balloon
    #- username: public
    #  password: publ1c
    #  type: public
    #- username: myicpc
    #  password: my1cpc
    #  type: spectator
    #- username: live
    #  password: l1ve
    #  type: analyst
    #- username: team1
    #  password: t3am
    #  type: team
    #  team_id: 1

# Contest(s) to configure in the CDS
CDS_CONTESTS:
  - path: nwerc18 # Path in the contest directory
    ccs:
      id: nwerc18 # ID of the contest if hosted at DOMJUDGE_URL
      # Or provide a absolute URL
      # url: https://www.domjudge.org/demoweb/api/contests/nwerc18
      username: admin
      password: admin

PRESCLIENT_CONTEST: nwerc18

# Sentry DSN URL
# SENTRY_DSN:

PROMETHEUS_PASS: secret-something-long-and-secret
